// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	models "github.com/afrizal423/mygram/app/models"
	mock "github.com/stretchr/testify/mock"
)

// ISocialMediaRepository is an autogenerated mock type for the ISocialMediaRepository type
type ISocialMediaRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: req, userID
func (_m *ISocialMediaRepository) Create(req models.RequestSocialMedia, userID uint) (models.SocialMedia, error) {
	ret := _m.Called(req, userID)

	var r0 models.SocialMedia
	var r1 error
	if rf, ok := ret.Get(0).(func(models.RequestSocialMedia, uint) (models.SocialMedia, error)); ok {
		return rf(req, userID)
	}
	if rf, ok := ret.Get(0).(func(models.RequestSocialMedia, uint) models.SocialMedia); ok {
		r0 = rf(req, userID)
	} else {
		r0 = ret.Get(0).(models.SocialMedia)
	}

	if rf, ok := ret.Get(1).(func(models.RequestSocialMedia, uint) error); ok {
		r1 = rf(req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id, userID
func (_m *ISocialMediaRepository) Delete(id uint, userID uint) (models.SocialMedia, error) {
	ret := _m.Called(id, userID)

	var r0 models.SocialMedia
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (models.SocialMedia, error)); ok {
		return rf(id, userID)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) models.SocialMedia); ok {
		r0 = rf(id, userID)
	} else {
		r0 = ret.Get(0).(models.SocialMedia)
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByUserId provides a mock function with given fields: userID
func (_m *ISocialMediaRepository) GetAllByUserId(userID uint) ([]models.SocialMedia, error) {
	ret := _m.Called(userID)

	var r0 []models.SocialMedia
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]models.SocialMedia, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []models.SocialMedia); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.SocialMedia)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserId provides a mock function with given fields: userID, id
func (_m *ISocialMediaRepository) GetByUserId(userID uint, id uint) (models.SocialMedia, error) {
	ret := _m.Called(userID, id)

	var r0 models.SocialMedia
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, uint) (models.SocialMedia, error)); ok {
		return rf(userID, id)
	}
	if rf, ok := ret.Get(0).(func(uint, uint) models.SocialMedia); ok {
		r0 = rf(userID, id)
	} else {
		r0 = ret.Get(0).(models.SocialMedia)
	}

	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(userID, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: socialMedia, id, userID
func (_m *ISocialMediaRepository) Update(socialMedia models.SocialMedia, id uint, userID uint) (models.SocialMedia, error) {
	ret := _m.Called(socialMedia, id, userID)

	var r0 models.SocialMedia
	var r1 error
	if rf, ok := ret.Get(0).(func(models.SocialMedia, uint, uint) (models.SocialMedia, error)); ok {
		return rf(socialMedia, id, userID)
	}
	if rf, ok := ret.Get(0).(func(models.SocialMedia, uint, uint) models.SocialMedia); ok {
		r0 = rf(socialMedia, id, userID)
	} else {
		r0 = ret.Get(0).(models.SocialMedia)
	}

	if rf, ok := ret.Get(1).(func(models.SocialMedia, uint, uint) error); ok {
		r1 = rf(socialMedia, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewISocialMediaRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewISocialMediaRepository creates a new instance of ISocialMediaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewISocialMediaRepository(t mockConstructorTestingTNewISocialMediaRepository) *ISocialMediaRepository {
	mock := &ISocialMediaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
